[2025-05-14 21:34:03,779] [Request ID: no-request-id] INFO - Trying to get service_id from URL parameters: {} (decorators.py:45)
[2025-05-14 21:34:03,788] [Request ID: no-request-id] INFO - Trying to get service from endpoint: roles.get_services (decorators.py:52)
[2025-05-14 21:34:03,789] [Request ID: no-request-id] INFO - Using auth_service for roles blueprint (decorators.py:56)
[2025-05-14 21:34:03,791] [Request ID: no-request-id] INFO - Found auth_service with ID: 1 (decorators.py:60)
[2025-05-14 21:34:03,793] [Request ID: no-request-id] INFO - Checking permissions ['service:read'] for service 1 (decorators.py:76)
[2025-05-14 21:34:13,505] [Request ID: no-request-id] INFO - Fetching profile for user: 3751881e-ee90-447d-8c29-3a8f91d6b60f (auth.py:284)
[2025-05-14 21:34:17,105] [Request ID: no-request-id] INFO - User login attempt (auth.py:114)
[2025-05-14 21:34:17,798] [Request ID: no-request-id] INFO - Login successful for user: aymane.benbouzid@gmail.com (auth.py:128)
[2025-05-14 21:34:17,806] [Request ID: no-request-id] INFO - Fetching profile for user: 3751881e-ee90-447d-8c29-3a8f91d6b60f (auth.py:284)
[2025-05-14 21:34:20,914] [Request ID: no-request-id] INFO - Fetching sessions for user: 4 (auth.py:228)
[2025-05-14 21:34:20,922] [Request ID: no-request-id] INFO - Fetching sessions for user: 4 (auth.py:228)
[2025-05-14 21:41:44,905] [Request ID: no-request-id] INFO - Fetching profile for user: 3751881e-ee90-447d-8c29-3a8f91d6b60f (auth.py:284)
[2025-05-14 21:42:16,362] [Request ID: no-request-id] INFO - Fetching profile for user: 3751881e-ee90-447d-8c29-3a8f91d6b60f (auth.py:284)
[2025-05-14 21:42:33,518] [Request ID: no-request-id] INFO - Fetching profile for user: 3751881e-ee90-447d-8c29-3a8f91d6b60f (auth.py:284)
[2025-05-15 08:17:53,195] [Request ID: N/A] INFO - Successfully connected to Redis (redis_service.py:33)
[2025-05-15 08:17:53,317] [Request ID: N/A] INFO - Database initialization completed successfully (__init__.py:105)
[2025-05-15 09:07:25,350] [Request ID: no-request-id] INFO - User login attempt (auth.py:114)
[2025-05-15 09:07:26,568] [Request ID: no-request-id] INFO - Login successful for user: aymane.benbouzid@gmail.com (auth.py:128)
[2025-05-15 09:07:42,777] [Request ID: no-request-id] INFO - User login attempt (auth.py:114)
[2025-05-15 09:07:43,435] [Request ID: no-request-id] INFO - Login successful for user: aymane.benbouzid@gmail.com (auth.py:128)
[2025-05-15 09:13:49,339] [Request ID: no-request-id] INFO - User login attempt (auth.py:114)
[2025-05-15 09:13:50,377] [Request ID: no-request-id] INFO - Login successful for user: aymane.benbouzid@gmail.com (auth.py:128)
[2025-05-15 09:14:15,121] [Request ID: no-request-id] INFO - Logging out user: 3751881e-ee90-447d-8c29-3a8f91d6b60f (auth.py:144)
[2025-05-15 09:14:15,126] [Request ID: no-request-id] INFO - Logout successful (auth.py:148)
[2025-05-15 09:31:28,279] [Request ID: no-request-id] INFO - User login attempt (auth.py:114)
[2025-05-15 09:31:29,364] [Request ID: no-request-id] INFO - Login successful for user: aymane.benbouzid@gmail.com (auth.py:128)
[2025-05-15 09:31:33,478] [Request ID: no-request-id] INFO - Logging out user: 3751881e-ee90-447d-8c29-3a8f91d6b60f (auth.py:144)
[2025-05-15 09:31:33,481] [Request ID: no-request-id] INFO - Logout successful (auth.py:148)
[2025-05-15 09:32:32,955] [Request ID: no-request-id] INFO - Registering new user (auth.py:47)
[2025-05-15 09:32:33,553] [Request ID: no-request-id] ERROR - Error registering user: An error occurred (InvalidPasswordException) when calling the SignUp operation: Password did not conform with policy: Password must have symbol characters (auth.py:87)
[2025-05-15 09:32:55,434] [Request ID: no-request-id] INFO - Registering new user (auth.py:47)
[2025-05-15 09:32:56,100] [Request ID: no-request-id] INFO - Cognito sign_up response: {'UserConfirmed': False, 'CodeDeliveryDetails': {'Destination': 'a***@i***', 'DeliveryMedium': 'EMAIL', 'AttributeName': 'email'}, 'UserSub': '647824c8-9021-700b-b1d7-521fd3a04148', 'ResponseMetadata': {'RequestId': 'a98a2d87-5d6e-46b3-9a5a-ef8ad348b950', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Thu, 15 May 2025 09:32:55 GMT', 'content-type': 'application/x-amz-json-1.1', 'content-length': '1186', 'connection': 'keep-alive', 'x-amzn-requestid': 'a98a2d87-5d6e-46b3-9a5a-ef8ad348b950'}, 'RetryAttempts': 0}} (auth.py:69)
[2025-05-15 09:32:56,344] [Request ID: no-request-id] INFO - User registered successfully (auth.py:77)
[2025-05-15 09:34:14,627] [Request ID: no-request-id] INFO - User login attempt (auth.py:114)
[2025-05-15 09:34:15,287] [Request ID: no-request-id] WARNING - Login failed, email needs verification: aymane.benbouzid.1@icloud.com (auth.py:131)
[2025-05-15 09:41:37,698] [Request ID: no-request-id] INFO - User login attempt (auth.py:114)
[2025-05-15 09:41:38,414] [Request ID: no-request-id] WARNING - Login failed, email needs verification: aymane.benbouzid.1@icloud.com (auth.py:131)
[2025-05-15 09:42:17,252] [Request ID: no-request-id] INFO - Registering new user (auth.py:47)
[2025-05-15 09:42:18,136] [Request ID: no-request-id] WARNING - User already exists in Cognito (auth.py:84)
[2025-05-15 09:44:58,129] [Request ID: no-request-id] INFO - Registering new user (auth.py:47)
[2025-05-15 09:44:59,277] [Request ID: no-request-id] INFO - Cognito sign_up response: {'UserConfirmed': False, 'CodeDeliveryDetails': {'Destination': 'a***@i***', 'DeliveryMedium': 'EMAIL', 'AttributeName': 'email'}, 'UserSub': '34b87428-d081-70b6-6fc9-a56b8edc5c2e', 'ResponseMetadata': {'RequestId': '031f691d-59d4-4bee-b815-34ba0200754f', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Thu, 15 May 2025 09:44:59 GMT', 'content-type': 'application/x-amz-json-1.1', 'content-length': '1186', 'connection': 'keep-alive', 'x-amzn-requestid': '031f691d-59d4-4bee-b815-34ba0200754f'}, 'RetryAttempts': 0}} (auth.py:69)
[2025-05-15 09:44:59,292] [Request ID: no-request-id] WARNING - User registration failed in DB: {'success': False, 'message': 'Email already registered'} (auth.py:80)
[2025-05-15 09:45:25,535] [Request ID: no-request-id] INFO - Registering new user (auth.py:47)
[2025-05-15 09:45:26,127] [Request ID: no-request-id] WARNING - User already exists in Cognito (auth.py:84)
[2025-05-15 09:46:13,731] [Request ID: no-request-id] INFO - Registering new user (auth.py:47)
[2025-05-15 09:46:14,308] [Request ID: no-request-id] WARNING - User already exists in Cognito (auth.py:84)
[2025-05-15 09:52:10,732] [Request ID: no-request-id] INFO - Registering new user (auth.py:47)
[2025-05-15 09:52:11,764] [Request ID: no-request-id] INFO - Cognito sign_up response: {'UserConfirmed': False, 'CodeDeliveryDetails': {'Destination': 'a***@i***', 'DeliveryMedium': 'EMAIL', 'AttributeName': 'email'}, 'UserSub': 'a4a84428-f0e1-7080-34b7-41c7f267ef91', 'ResponseMetadata': {'RequestId': 'b16490c1-49d4-4e99-bd71-c0aa9a1333e4', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Thu, 15 May 2025 09:52:11 GMT', 'content-type': 'application/x-amz-json-1.1', 'content-length': '1186', 'connection': 'keep-alive', 'x-amzn-requestid': 'b16490c1-49d4-4e99-bd71-c0aa9a1333e4'}, 'RetryAttempts': 0}} (auth.py:69)
[2025-05-15 09:52:12,003] [Request ID: no-request-id] INFO - User registered successfully (auth.py:77)
[2025-05-15 09:52:30,429] [Request ID: no-request-id] INFO - User login attempt (auth.py:114)
[2025-05-15 09:52:31,062] [Request ID: no-request-id] WARNING - Login failed, email needs verification: aymane.benbouzid@icloud.com (auth.py:131)
[2025-05-15 09:54:34,097] [Request ID: no-request-id] INFO - Verifying email with token (auth.py:94)
[2025-05-15 09:54:34,738] [Request ID: no-request-id] INFO - Email verified successfully (auth.py:104)
[2025-05-15 09:55:31,185] [Request ID: no-request-id] INFO - User login attempt (auth.py:114)
[2025-05-15 09:55:31,551] [Request ID: no-request-id] WARNING - Login failed: aymane.benbouzid.1@icloud.com (auth.py:134)
[2025-05-15 09:55:36,575] [Request ID: no-request-id] INFO - User login attempt (auth.py:114)
[2025-05-15 09:55:36,954] [Request ID: no-request-id] WARNING - Login failed, email needs verification: aymane.benbouzid@icloud.com (auth.py:131)
[2025-05-16 08:34:03,269] [Request ID: N/A] INFO - Successfully connected to Redis (redis_service.py:33)
[2025-05-16 08:34:03,440] [Request ID: N/A] INFO - Database initialization completed successfully (__init__.py:105)
[2025-05-16 11:33:47,846] [Request ID: N/A] INFO - Successfully connected to Redis (redis_service.py:33)
[2025-05-16 11:33:47,920] [Request ID: N/A] INFO - Database initialization completed successfully (__init__.py:105)
[2025-05-16 15:33:54,012] [Request ID: N/A] INFO - Successfully connected to Redis (redis_service.py:33)
[2025-05-16 15:33:54,083] [Request ID: N/A] INFO - Database initialization completed successfully (__init__.py:105)
[2025-05-17 11:34:04,342] [Request ID: N/A] INFO - Successfully connected to Redis (redis_service.py:33)
[2025-05-17 11:34:04,472] [Request ID: N/A] INFO - Database initialization completed successfully (__init__.py:105)
[2025-05-17 15:33:52,607] [Request ID: N/A] INFO - Successfully connected to Redis (redis_service.py:33)
[2025-05-17 15:33:52,673] [Request ID: N/A] INFO - Database initialization completed successfully (__init__.py:105)
[2025-05-18 11:34:05,308] [Request ID: N/A] INFO - Successfully connected to Redis (redis_service.py:33)
[2025-05-18 11:34:05,425] [Request ID: N/A] INFO - Database initialization completed successfully (__init__.py:105)
[2025-05-18 15:34:03,816] [Request ID: N/A] INFO - Successfully connected to Redis (redis_service.py:33)
[2025-05-18 15:34:03,886] [Request ID: N/A] INFO - Database initialization completed successfully (__init__.py:105)
[2025-05-19 11:34:15,079] [Request ID: N/A] INFO - Successfully connected to Redis (redis_service.py:33)
[2025-05-19 11:34:15,199] [Request ID: N/A] INFO - Database initialization completed successfully (__init__.py:105)
